# nixpacks.toml
# This file explicitly configures Nixpacks for a Python application.

[phases.setup]
# Ensure python3 is available in the build environment
pkgs = ["python3"]

[phases.build]
# Define the exact command to install your Python dependencies
# This explicitly tells Nixpacks to run pip install
cmds = ["pip install -r requirements.txt"]

[phases.start]
# Define the exact command to start your Flask application
# This explicitly uses python3 to run gunicorn as a module
cmd = "python3 -m gunicorn app:app"

[variables]
# This line tells Nixpacks to use a specific Python version
PYTHON_VERSION = "3.10" # OR "3.11" - try 3.10 first