# nixpacks.toml
# This file explicitly configures Nixpacks for a Python application.

[phases.setup]
# Force a specific Python version (3.10) for the build and runtime environment.
# 'python3' ensures a generic Python 3, and 'python@python3.10' forces the specific version.
# 'gcc' is included as it's often needed for compiling certain Python packages.
pkgs = ["python3", "python@python3.10", "gcc"]

[phases.build]
# Define the exact command to install your Python dependencies
cmds = ["pip install -r requirements.txt"]

[phases.start]
# Define the exact command to start your Flask application
# Keep using 'python3 -m gunicorn' for robustness.
cmd = "python3 -m gunicorn app:app"

# Remove the [variables] section if it existed for PYTHON_VERSION.
# It seems to not be effective for controlling the base Python version for Nixpacks.